version: '3.8'


networks:
  docker_compose_for_development_store-mng-sys-net:
    external: true
  docker_compose_for_development_shared-blocklist-net:
    external: true
  docker_compose_for_development_ethereum-payment-net:
    external: true

services:
  couriers-service:
    build:
      context: ../../development/store_management_system/couriers_service
      dockerfile: ./Dockerfile
    ports:
      - 5003:5000
    # depends_on:
    #   migration-db-store-management:
    #     condition: service_completed_successfully
    #   blocklist-redis:
    #     condition: service_healthy
    environment:
      # - DB_STORE_MANAGEMENT_URI=*store_mng_db_env
      - DB_STORE_MANAGEMENT_URI=mysql+pymysql://root:etf@db-store-management:3306/store_management
      - JWT_SECRET_KEY=JWT_SECRET_DEV_KEY
      - REDIS_BLOCKLIST_HOST=blocklist-redis
      - REDIS_BLOCKLIST_PORT=6379
      - REDIS_BLOCKLIST_DB=0
      - LOGGING_LEVEL=DEBUG
      - WEB3_SIMULATOR_URI=http://ethereum-simulator:8545
    volumes:
      - type: bind
        source: ./logs/store_management_system/couriers_service
        target: /usr/service/logs/
    networks:
      - docker_compose_for_development_store-mng-sys-net
      - docker_compose_for_development_shared-blocklist-net
      - docker_compose_for_development_ethereum-payment-net
